// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd5XksqZ7ynknmoLAzkonb5Ma9FxD6Q5M',
    appId: '1:907279629187:web:287ef178378e752472d4b6',
    messagingSenderId: '907279629187',
    projectId: 'clearview-3078c',
    authDomain: 'clearview-3078c.firebaseapp.com',
    storageBucket: 'clearview-3078c.firebasestorage.app',
    measurementId: 'G-S3EN6HB8Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEfT5zsvpe-e80ntNW5EF1w5yvL80SCE',
    appId: '1:907279629187:android:223001550f670dc672d4b6',
    messagingSenderId: '907279629187',
    projectId: 'clearview-3078c',
    storageBucket: 'clearview-3078c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLt9S2zQSYFmSDq8EVS1mql1aeN64y3So',
    appId: '1:907279629187:ios:00422ad5b7dd276272d4b6',
    messagingSenderId: '907279629187',
    projectId: 'clearview-3078c',
    storageBucket: 'clearview-3078c.firebasestorage.app',
    iosBundleId: 'com.example.clearview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLt9S2zQSYFmSDq8EVS1mql1aeN64y3So',
    appId: '1:907279629187:ios:00422ad5b7dd276272d4b6',
    messagingSenderId: '907279629187',
    projectId: 'clearview-3078c',
    storageBucket: 'clearview-3078c.firebasestorage.app',
    iosBundleId: 'com.example.clearview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd5XksqZ7ynknmoLAzkonb5Ma9FxD6Q5M',
    appId: '1:907279629187:web:fc79f68ce54355d872d4b6',
    messagingSenderId: '907279629187',
    projectId: 'clearview-3078c',
    authDomain: 'clearview-3078c.firebaseapp.com',
    storageBucket: 'clearview-3078c.firebasestorage.app',
    measurementId: 'G-V7RRHMWYE9',
  );
}
